# Worksheet 04

Name:  Mariano Majano Amaya
UID: U56063451

### Topics

- Distance & Similarity

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

- p is an arbitrary parameter that must be >= 1
- d is the number of dimensions x and y have

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

The main difference between these distance metrics is how they measure distances; when p=2 it is Euclidean distance and when p=1 it is Manhattan distance. Euclidean distance calculates the shortest straight-line distance, while Manhattan distance calculates the distance along a grid-like path.

Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

The distance will get very close but never get exactly to 1 as p gets very large.

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

No. Counter-example:  
Suppose A(0,0), B(1,0), C(0,1). Then D(B,A) = D(A,C) = 1 and D(B,C) = $2^{1/p}$. If p < 1, then 1/p > 1. So D(B,C) > D(B,A) + D (A,C). However, this violates the triangular inequality, so it would not be a distance function.

e) when would you use cosine similarity over the euclidan distance?

When direction matters more than magnitude, e.g: a dataset like a document and an abstract describing that document would yield a large Euclidean distance but a small cosine distance as they both talk about the same topic.

f) what does the jaccard distance account for that the manhattan distance doesn't?

The Jaccard also takes into consideration the size of the intersection which Manhattan doesn't do. More technically, the Jaccard distance considers the relative similarity of sets by considering the intersection over the union.

#### Part 2

Consider the following two sentences:

In [ ]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [ ]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [ ]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['hello', 'Bob', 'is', 'name', 'my', 'Alice']
[1, 0, 1, 1, 1, 1]


Let's add a new sentence to our corpus:

In [ ]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [7]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"
s3 = "hi my name is Claude"
corpus = [s1, s2, s3]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)



['is', 'Claude', 'name', 'my', 'hello', 'Alice', 'hi', 'Bob']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [8]:
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)
v2 = [1 if x in s2 else 0 for x in all_words]
print(v2)
v3 = [1 if x in s3 else 0 for x in all_words]
print(v3)

['is', 'Claude', 'name', 'my', 'hello', 'Alice', 'hi', 'Bob']
[1, 0, 1, 1, 1, 1, 0, 0]
[1, 0, 1, 1, 1, 0, 0, 1]
[1, 1, 1, 1, 0, 0, 1, 0]


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [12]:
def manhattan_distance(vector1, vector2):
    return sum(abs(val1 - val2) for val1, val2 in zip(vector1, vector2))


distance_v1_v2 = manhattan_distance(v1, v2)
distance_v1_v3 = manhattan_distance(v1, v3)
distance_v2_v3 = manhattan_distance(v2, v3)

distances = {
    "v1-v2": distance_v1_v2,
    "v1-v3": distance_v1_v3,
    "v2-v3": distance_v2_v3
}

most_similar = min(distances, key=distances.get)

print("v1/v2 dist:", distance_v1_v2, "\nv1/v3 dist:", distance_v1_v3, "\nv2/v3 dist:", distance_v2_v3, "\nmost similar:", most_similar)

v1/v2 dist: 2 
v1/v3 dist: 4 
v2/v3 dist: 4 
most similar: v1-v2


d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [17]:
corpus = ["hi Alice", "hello Claude", "Bob my name is Claude", "hi Claude my name is Alice", "hello Bob"]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)

matrix = [[1 if word in sentence else 0 for word in all_words] for sentence in corpus]

for vector in matrix:
    print(vector)

['Claude', 'is', 'my', 'hello', 'name', 'Alice', 'hi', 'Bob']
[0, 0, 0, 0, 0, 1, 1, 0]
[1, 0, 0, 1, 0, 0, 0, 0]
[1, 1, 1, 0, 1, 0, 0, 1]
[1, 1, 1, 0, 1, 1, 1, 0]
[0, 0, 0, 1, 0, 0, 0, 1]


e) How many rows and columns does this matrix have?

In [18]:
rows = len(matrix)
cols = len(matrix[0])

print("rows:", rows)
print("columns", cols)

rows: 5
columns 8


f) When using the Manhattan distance, which two sentences are the most similar?

In [19]:
minimum = manhattan_dist(matrix[0], matrix[1])
vectors = (0, 1)
for i in range(1, len(matrix)):
    for j in range(i, len(matrix)):
        if i != j:
            new_min = manhattan_dist(matrix[i], matrix[j])
            if minimum > new_min:
                minimum = new_min
                vectors = (i, j)
print(vectors)
print(matrix[vectors[0]], matrix[vectors[1]])

(1, 4)
[1, 0, 0, 1, 0, 0, 0, 0] [0, 0, 0, 1, 0, 0, 0, 1]


#### Part 3 Challenge

Given a set of graphs $\mathcal{G}$, each graph $G \in \mathcal{G}$ is defined over the same set of nodes $V$. The graphs are represented by their adjacency matrices, which are 2D arrays where each element indicates whether a pair of nodes is connected by an edge.

Your task is to compute the pairwise distances between these graphs based on a specific distance metric. The distance $d(G, G')$ between two graphs $G = (V, E)$ and $G' = (V, E')$ is defined as the sum of the number of edges in $G$ but not in $G'$, and the number of edges in $G'$ but not in $G$. Mathematically, this can be expressed as:

$$
d(G, G') = |E \setminus E'| + |E' \setminus E|.
$$

##### Requirements:
1. **Input**: Should take a list of 2D numpy arrays as input. Each array represents the adjacency matrix of a graph.

2. **Output**: Should output a pairwise distance matrix. If there are $n$ graphs in the input list, the output should be an $n \times n$ matrix where the entry at position $(i, j)$ represents the distance between the $i^{th}$ and $j^{th}$ graph.

In [20]:
import numpy as np

def compute_graph_distance_matrix(graphs):
    num_graphs = len(graphs)
    distance_matrix = np.zeros((num_graphs, num_graphs), dtype=int)
    
    # Compute pairwise distances
    for i in range(num_graphs):
        for j in range(i+1, num_graphs):
            # Calculate the symmetric difference between two adjacency matrices
            distance = np.sum(np.abs(graphs[i] - graphs[j]))
            distance_matrix[i][j] = distance
            distance_matrix[j][i] = distance  # The distance matrix is symmetric
    
    return distance_matrix

# Define adjacency matrices for each graph
graph1 = np.array([
    [0, 1, 1, 0],
    [1, 0, 1, 0],
    [1, 1, 0, 1],
    [0, 0, 1, 0]
])

graph2 = np.array([
    [0, 1, 0, 1],
    [1, 0, 1, 1],
    [0, 1, 0, 1],
    [1, 1, 1, 0]
])

graph3 = np.array([
    [0, 0, 1, 0],
    [0, 0, 1, 0],
    [1, 1, 0, 1],
    [0, 0, 1, 0]
])

# Create a list of graphs
graphs = [graph1, graph2, graph3]

# Compute the pairwise distance matrix
distance_matrix = compute_graph_distance_matrix(graphs)
print(distance_matrix)


[[0 6 2]
 [6 0 8]
 [2 8 0]]
